---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            # Login to the hub
            - name: Login to Docket Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            # Checkout all actions
            - name: Checkout
              uses: actions/checkout@v2
            # Run unit test
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py test"
            # Linting
            - name: Lint
              run: docker-compose run -- rm app sh -c "flake8"